### PR TITLE
fix: add stop function to planet service

### PR DESCRIPTION
**Pull request by mario56**

### CODE REVIEW

**Comment by why520crazy** [comment]
Perfect，good issue for your contribution.

Please add some unit test?

**Comment by mario56** [comment]
> Perfect，good issue for your contribution.
> 
> Please add some unit test?

had add stop unit test

**Comment by why520crazy** [comment]
test this please

**Comment by why520crazy** [comment]
please bump @worktile/planet to `1.2.0`

**Comment by why520crazy** [comment]
@all-contributors please add @mario56 for code

**Pull request merged**
